version: "3"

services:
    abstruse:
        image: bleenco/abstruse
        ports:
            - "6500:6500"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "~/abstruse:/root/abstruse"
