version: "3"

services:
    gogs:
        image: gogs/gogs
        container_name: gogs
        volumes:
            - "/var/gogs:/data"
        ports:
            - "3000:3000"
            - "3022:3022"

    abstruse:
        image: bleenco/abstruse
        container_name: abstruse
        ports:
            - "6500:6500"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "~/abstruse:/root/abstruse"

    teamcity:
        image: jetbrains/teamcity-server
        container_name: teamcity
        ports:
            - "8111:8111"
        volumes:
            - "~/.teamcity/server/data:/data/teamcity_server/datadir"
            - "~/.teamcity/server/logs:/opt/teamcity/lots"

    teamcity-agent:
        image: jetbrains/teamcity-agent:2020.2.1-linux-sudo
        user: "0"
        deploy:
            mode: replicated
            replicas: 4
        environment:
            - SERVER_URL=10.0.0.30:8111
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "/usr/bin/docker:/usr/bin/docker"
            - "~/.teamcity/agent/conf:/data/teamcity_agent/conf"
            - "~/.teamcity/agent/work:/opt/buildagent/work"
            - "~/.teamcity/agent/temp:/opt/buildagent/temp"
            - "~/.teamcity/agent/tools:/opt/buildagent/tools"
            - "~/.teamcity/agent/plugins:/opt/buildagent/plugins"
            - "~/.teamcity/agent/system:/opt/buildagent/system"
