version: "3"

services:
    gogs:
        image: gogs/gogs
        container_name: gogs
        volumes:
            - "/var/gogs:/data"
        ports:
            - "3000:3000"
            - "3022:3022"

    teamcity:
        image: jetbrains/teamcity-server
        container_name: teamcity
        ports:
            - "8111:8111"
        volumes:
            - "~/.teamcity/server/data:/data/teamcity_server/datadir"
            - "~/.teamcity/server/logs:/opt/teamcity/lots"

    teamcity-agent:
        image: jetbrains/teamcity-agent:2020.2.1-linux-sudo
        user: "0"
        environment:
            - SERVER_URL=10.0.0.20:8111
            - DOCKER_IN_DOCKER=start
        volumes:
            - "/opt/buildagent/temp:/opt/buildagent/temp"
            - "/opt/buildagent/work:/opt/buildagent/work"
            - "/usr/bin/docker:/usr/bin/docker"
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "teamcity-agent-config:/data/teamcity_agent/conf"

volumes:
    teamcity-agent-config:
